# active profile
spring:
  profiles:
    active: dev-mysql

---
# profile group
spring:
  profiles:
    group:
      dev-h2: "local-mem-h2, local-log"
      dev-mysql: "local-ssd-mysql, local-log"

---
# local-mem-h2
spring:
  config:
    activate:
      on-profile: local-mem-h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sidedish;mode=MYSQL;
    username: sa
    password:
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:ddl.sql
      data-locations: classpath:dml.sql
  h2:
    console:
      enabled: true

---
# local-ssd-mysql
spring:
  config:
    activate:
      on-profile: local-ssd-mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sidedish
    username: root
    password:
  sql:
    init:
      platform: mysql
      mode: always
      schema-locations: classpath:ddl.sql
      data-locations: classpath:dml.sql

---
# log-group
spring:
  profiles:
    group:
      local-log: "console-log, low-level-log"
